Repository SWM-YouQuiz/User-Service, pull requests merged in 2023-08, with the labels that each got.

#13 [YOUQ-121] 퀴즈 좋아요 이벤트 Consumer 구현
  src/main/kotlin/com/youquiz/user/adapter/consumer/UserConsumer.kt
  src/main/kotlin/com/youquiz/user/domain/User.kt
  src/main/kotlin/com/youquiz/user/event/LikeEvent.kt
  src/test/kotlin/com/youquiz/user/domain/UserTest.kt
Labels: Feat

#15 [YOUQ-123] Jenkins CI 연동
  Dockerfile
  Jenkinsfile
Labels: CI / CD

#17 [#16] 모든 API 엔드포인트 prefix 수정
  src/main/kotlin/com/quizit/user/global/config/SecurityConfiguration.kt
  src/main/kotlin/com/quizit/user/router/UserRouter.kt
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/kotlin/com/quizit/user/util/BaseControllerTest.kt
Labels: Feat, Fix

#19 [YOUQ-120] Argo CD 연동
  Jenkinsfile
Labels: CI / CD

#21 [#20] 유저 프로필 수정 및 탈퇴 API 구현
  src/main/kotlin/com/quizit/user/dto/request/ChangePasswordRequest.kt
  src/main/kotlin/com/quizit/user/dto/request/UpdateUserByIdRequest.kt
  src/main/kotlin/com/quizit/user/exception/PasswordNotMatchException.kt
  src/main/kotlin/com/quizit/user/exception/PermissionDeniedException.kt
  src/main/kotlin/com/quizit/user/handler/UserHandler.kt
  src/main/kotlin/com/quizit/user/router/UserRouter.kt
  src/main/kotlin/com/quizit/user/service/UserService.kt
  src/test/kotlin/com/quizit/user/controller/UserControllerTest.kt
  src/test/kotlin/com/quizit/user/fixture/UserFixture.kt
  src/test/kotlin/com/quizit/user/service/UserServiceTest.kt
Labels: Feat

#25 [YOUQ-136] 유저 랭킹 API 구현
  src/main/kotlin/com/quizit/user/handler/UserHandler.kt
  src/main/kotlin/com/quizit/user/repository/UserRepository.kt
  src/main/kotlin/com/quizit/user/router/UserRouter.kt
  src/main/kotlin/com/quizit/user/service/UserService.kt
  src/test/kotlin/com/quizit/user/config/SecurityTestConfiguration.kt
  src/test/kotlin/com/quizit/user/controller/UserControllerTest.kt
  src/test/kotlin/com/quizit/user/service/UserServiceTest.kt
Labels: Feat
